version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.Backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
